//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tic_Toc_Toe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Match
    {
        public int games_match_id { get; set; }
        public Nullable<int> games_id { get; set; }
        public Nullable<int> player1_score { get; set; }
        public Nullable<int> player2_score { get; set; }
        public Nullable<int> player_id { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
